# Generated by Django 4.1.1 on 2022-10-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_varified',
            field=models.BooleanField(default=False),
        ),
    ]
