# Generated by Django 4.1.1 on 2022-10-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_user_is_email_varified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
