# Generated by Django 4.1.1 on 2022-11-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccon_desc_master',
            fields=[
                ('cdm_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('ccon_desc_title', models.CharField(blank=True, max_length=150, null=True)),
                ('ccon_desc_sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('course_slno', models.CharField(blank=True, max_length=150, null=True)),
                ('content_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('course_short_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('course_length', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_col_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_col_id', models.IntegerField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('col_data_type', models.CharField(max_length=150)),
                ('col_desc', models.TextField(max_length=500)),
                ('col_classi', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Table_info_dtl',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=150)),
                ('table_description', models.TextField(max_length=500)),
                ('table_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Table_data_info',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_data', models.TextField(max_length=500)),
                ('col_data_type', models.CharField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('table_col_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.table_col_info')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.table_info_dtl')),
            ],
        ),
        migrations.AddField(
            model_name='table_col_info',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.table_info_dtl'),
        ),
        migrations.CreateModel(
            name='ccon_mcq_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_question', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_type', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_comments', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_q_slno', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_q_multi', models.BooleanField(blank=True, null=True)),
                ('mcq_id', models.IntegerField(blank=True, null=True)),
                ('cdm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.ccon_desc_master')),
            ],
        ),
        migrations.CreateModel(
            name='ccon_mcq_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_choice', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_choice_slno', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_choice_type', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_q_image_url', models.URLField(blank=True, max_length=150, null=True)),
                ('mcq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.ccon_mcq_mst')),
            ],
        ),
        migrations.CreateModel(
            name='ccon_desc_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd_id', models.IntegerField(blank=True, null=True)),
                ('contents_body', models.CharField(blank=True, max_length=150, null=True)),
                ('contents_type', models.CharField(blank=True, max_length=150, null=True)),
                ('image_url', models.URLField(blank=True, max_length=150, null=True)),
                ('Image_type', models.CharField(blank=True, max_length=150, null=True)),
                ('cdm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.ccon_desc_master')),
            ],
        ),
    ]
