# Generated by Django 3.2.18 on 2025-02-16 18:53

import courseapp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccon_desc_master',
            fields=[
                ('cdm_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('ccon_desc_title', models.CharField(blank=True, max_length=150, null=True)),
                ('ccon_desc_sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('course_slno', models.CharField(blank=True, max_length=150, null=True)),
                ('content_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('course_short_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('course_length', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path_csv)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationEventUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path_invitation)),
            ],
        ),
        migrations.CreateModel(
            name='JsonDynamicModel',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('col_data_type', models.CharField(default='String', max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('jsonfield', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonfield', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path_json)),
            ],
        ),
        migrations.CreateModel(
            name='Table_col_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('col_data_type', models.CharField(max_length=150)),
                ('col_desc', models.TextField(max_length=500)),
                ('col_classi', models.CharField(max_length=150)),
                ('col_visible', models.CharField(default='True', max_length=50)),
                ('col_entry_time', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 16, 12, 53, 33, 578434))),
            ],
        ),
        migrations.CreateModel(
            name='Table_col_info2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=150)),
                ('col_data_type', models.CharField(max_length=150)),
                ('col_desc', models.TextField(max_length=500)),
                ('col_classi', models.CharField(max_length=150)),
                ('col_visible', models.CharField(default='True', max_length=50)),
                ('col_entry_time', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_col_info3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=150)),
                ('col_data_type', models.CharField(max_length=150)),
                ('col_desc', models.TextField(max_length=500)),
                ('col_classi', models.CharField(max_length=150)),
                ('col_visible', models.CharField(default='True', max_length=50)),
                ('col_entry_time', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_data_info',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('vflag', models.CharField(blank=True, max_length=150, null=True)),
                ('column_data', models.TextField()),
                ('col_data_type', models.CharField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 16, 12, 53, 33, 578434))),
            ],
        ),
        migrations.CreateModel(
            name='Table_data_info2',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('vflag', models.CharField(blank=True, max_length=150, null=True)),
                ('column_data', models.TextField()),
                ('col_data_type', models.CharField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_data_info3',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('vflag', models.CharField(blank=True, max_length=150, null=True)),
                ('column_data', models.TextField()),
                ('col_data_type', models.CharField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_info_dtl',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=150)),
                ('table_description', models.TextField(max_length=500)),
                ('table_type', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 16, 12, 53, 33, 578434))),
            ],
        ),
        migrations.CreateModel(
            name='Table_info_dtl2',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=150)),
                ('table_description', models.TextField(max_length=500)),
                ('table_type', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_info_dtl3',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=150)),
                ('table_description', models.TextField(max_length=500)),
                ('table_type', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='ccon_mcq_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_question', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_type', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_comments', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_q_slno', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_q_multi', models.BooleanField(blank=True, null=True)),
                ('mcq_id', models.IntegerField(blank=True, null=True)),
                ('cdm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.ccon_desc_master')),
            ],
        ),
        migrations.CreateModel(
            name='ccon_mcq_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_choice', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_choice_slno', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_choice_type', models.CharField(blank=True, max_length=150, null=True)),
                ('mcq_q_image_url', models.URLField(blank=True, max_length=150, null=True)),
                ('mcq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.ccon_mcq_mst')),
            ],
        ),
        migrations.CreateModel(
            name='ccon_desc_dtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd_id', models.IntegerField(blank=True, null=True)),
                ('contents_body', models.CharField(blank=True, max_length=150, null=True)),
                ('contents_type', models.CharField(blank=True, max_length=150, null=True)),
                ('image_url', models.URLField(blank=True, max_length=150, null=True)),
                ('Image_type', models.CharField(blank=True, max_length=150, null=True)),
                ('cdm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.ccon_desc_master')),
            ],
        ),
    ]
