# Generated by Django 4.1.1 on 2022-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_data_info',
            name='table_col_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='table_id',
            field=models.IntegerField(),
        ),
    ]
