# Generated by Django 3.2.18 on 2025-02-19 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 13, 47, 37, 861701)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 13, 47, 37, 863696)),
        ),
        migrations.AlterField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 13, 47, 37, 860703)),
        ),
    ]
