# Generated by Django 3.2.16 on 2022-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_alter_table_data_info_table_col_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='table_id',
            field=models.IntegerField(),
        ),
    ]
