# Generated by Django 3.2.16 on 2022-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_alter_table_col_info_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_col_info',
            name='col_entry_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='table_col_info',
            name='col_visible',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
