# Generated by Django 3.2.18 on 2025-02-19 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_auto_20250219_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 14, 43, 17, 779978)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 14, 43, 17, 781972)),
        ),
        migrations.AlterField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 14, 43, 17, 778980)),
        ),
    ]
