# Generated by Django 3.2.16 on 2022-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_auto_20221121_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data_info',
            name='table_ref_id',
            field=models.IntegerField(default=1),
        ),
    ]
