# Generated by Django 3.2.18 on 2025-02-19 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_auto_20250219_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 14, 45, 7, 543666)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 14, 45, 7, 544664)),
        ),
        migrations.AlterField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 14, 45, 7, 542669)),
        ),
    ]
