# Generated by Django 3.2.16 on 2022-12-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0005_table_data_info_table_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data_info',
            name='slno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_data_info',
            name='tab_rel_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table_data_info',
            name='vflag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
