# Generated by Django 3.2.16 on 2022-12-20 13:38

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0006_auto_20221208_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_file_name', models.ImageField(blank=True, null=True, upload_to=courseapp.models.upload_file_path)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path)),
            ],
        ),
    ]
