# Generated by Django 3.2.16 on 2022-12-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonfield', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
