# Generated by Django 3.2.16 on 2023-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_jsonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_data_info',
            name='column_data',
            field=models.TextField(),
        ),
    ]
