# Generated by Django 3.2.18 on 2025-05-26 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0008_auto_20250219_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_col_info',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table_col_info2',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table_col_info3',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table_info_dtl',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table_info_dtl2',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='table_info_dtl3',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 26, 11, 15, 12, 714701)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 26, 11, 15, 12, 715700)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='table_data_info2',
            name='user_id',
            field=models.CharField(blank=True, default='1', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 26, 11, 15, 12, 713704)),
        ),
    ]
