# Generated by Django 3.2.16 on 2023-01-21 17:33

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0009_alter_table_data_info_column_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationEventUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path_invitation)),
            ],
        ),
    ]
