# Generated by Django 3.2.16 on 2023-02-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0010_invitationeventuploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data_info',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
