# Generated by Django 3.2.18 on 2023-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0011_table_data_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationeventuploadfile',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
