# Generated by Django 3.2.18 on 2023-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0012_invitationeventuploadfile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='upload_file_name',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
