# Generated by Django 3.2.18 on 2023-03-19 19:28

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0015_auto_20230319_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='upload_file_name',
            field=models.ImageField(blank=True, null=True, upload_to=courseapp.models.upload_file_path),
        ),
    ]
