# Generated by Django 3.2.18 on 2023-03-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0016_uploadfile_upload_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='upload_file_name',
        ),
    ]
