# Generated by Django 3.2.18 on 2023-07-30 20:08

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0017_remove_uploadfile_upload_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to=courseapp.models.upload_file_path_csv)),
            ],
        ),
    ]
