# Generated by Django 3.2.18 on 2023-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0019_jsonuploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='col_visible',
            field=models.CharField(default='True', max_length=50),
        ),
    ]
