# Generated by Django 3.2.18 on 2024-01-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0020_alter_table_col_info_col_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_data_info',
            name='table_ref_id',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
