# Generated by Django 3.2.18 on 2024-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0021_alter_table_data_info_table_ref_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDynamicModel',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('col_data_type', models.CharField(default='String', max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('jsonfield', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
