# Generated by Django 3.2.18 on 2024-02-10 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0022_jsondynamicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_col_info2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=150)),
                ('col_data_type', models.CharField(max_length=150)),
                ('col_desc', models.TextField(max_length=500)),
                ('col_classi', models.CharField(max_length=150)),
                ('col_visible', models.CharField(default='True', max_length=50)),
                ('col_entry_time', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_col_info3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('column_name', models.CharField(max_length=150)),
                ('col_data_type', models.CharField(max_length=150)),
                ('col_desc', models.TextField(max_length=500)),
                ('col_classi', models.CharField(max_length=150)),
                ('col_visible', models.CharField(default='True', max_length=50)),
                ('col_entry_time', models.DateField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_data_info2',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('vflag', models.CharField(blank=True, max_length=150, null=True)),
                ('column_data', models.TextField()),
                ('col_data_type', models.CharField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_data_info3',
            fields=[
                ('table_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('table_id', models.IntegerField()),
                ('table_col_id', models.IntegerField()),
                ('table_ref_id', models.CharField(default=1, max_length=250)),
                ('tab_rel_id', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(blank=True, max_length=150, null=True)),
                ('vflag', models.CharField(blank=True, max_length=150, null=True)),
                ('column_data', models.TextField()),
                ('col_data_type', models.CharField(max_length=150)),
                ('column_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_info_dtl2',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=150)),
                ('table_description', models.TextField(max_length=500)),
                ('table_type', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_info_dtl3',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=150)),
                ('table_description', models.TextField(max_length=500)),
                ('table_type', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 15, 43, 11, 79874)),
        ),
        migrations.AddField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 15, 43, 11, 80294)),
        ),
        migrations.AddField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 10, 15, 43, 11, 79563)),
        ),
    ]
