# Generated by Django 3.2.18 on 2024-04-18 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0024_alter_table_col_info_date_alter_table_data_info_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 14, 17, 12, 746356)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 14, 17, 12, 746982)),
        ),
        migrations.AlterField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 14, 17, 12, 745959)),
        ),
    ]
