# Generated by Django 3.2.18 on 2024-11-06 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0026_auto_20241106_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_col_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 6, 20, 49, 35, 228353)),
        ),
        migrations.AlterField(
            model_name='table_data_info',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 6, 20, 49, 35, 228847)),
        ),
        migrations.AlterField(
            model_name='table_info_dtl',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 6, 20, 49, 35, 227943)),
        ),
    ]
