"""
Django settings for idriveneducation project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

import pymysql 
pymysql.install_as_MySQLdb()

os.environ['OPENBLAS_NUM_THREADS'] = '1'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gmx=d_t2pa4=z3f(ni+4qi+60+-son9=xd3lwb!qiv%$csi$5m'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False

DEBUG = True

ALLOWED_HOSTS = ['*', '3.145.97.244', '3.145.97.244:8000', '127.0.0.1','localhost', 'itb-usa.a2hosted.com', 'https://aifin.vercel.app/', 'aifin.vercel.app', 'http://3.145.97.244:8000/graphql', '3.142.198.211', 'www.genflyo.com', 'genflyo.com']



AUTH_USER_MODEL = 'accountapp.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # local apps
    'drivenapp',
    'accountapp',
    # 'courseapp.apps.CourseappConfig',
    'courseapp',

    'emailserviceapp',

    'anymail',
    
    # 3rd party apps
    'rest_framework',
    'corsheaders',
    # 'gTTS',
    "graphene_django",
    'graphql_jwt',
    'channels',
    
    "django_filters",
    "django_apscheduler",
    
    'django_crontab',
    
]


CRONJOBS = [
    ('*/1 * * * *', 'courseapp.cron.job_start'),
]

# graphql
GRAPHENE = {
    "SCHEMA": "idriveneducation.schema.schema",
    "MIDDLEWARE": [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ],
}

AUTHENTICATION_BACKENDS = [
    "graphql_jwt.backends.JSONWebTokenBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Simple JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),   
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}



SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

PASSWORD_RESET_TIMEOUT=900          # 900 Sec = 15 Min

CORS_ALLOW_ALL_ORIGINS = True





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    
   
]

ROOT_URLCONF = 'idriveneducation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR, "templates")
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'idriveneducation.wsgi.application'
ASGI_APPLICATION = 'idriveneducation.router.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'itbusaah_idriveneducationdb',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',   
        'PORT': '3306',
    }
}








CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_DIRS = [
    BASE_DIR/'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ANYMAIL = {
#     # (exact settings here depend on your ESP...)
#     "MAILGUN_API_KEY": "3042ba401bfbda19d267771e30154333-e298dd8e-4f59d3ef",
#     "MAILGUN_SENDER_DOMAIN": 'sandboxd62d1a154de345f58e3a954ce851182c.mailgun.org',  # your Mailgun domain, if needed
# }
# EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
# EMAIL_HOST = 'smtp.mailgun.org'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587 
# EMAIL_HOST_USER = 'postmaster@sandboxd62d1a154de345f58e3a954ce851182c.mailgun.org'
# EMAIL_HOST_PASSWORD = 'cfc9229818c574d34ac289e89af69d83-e298dd8e-341f7547'
# DEFAULT_FROM_EMAIL = 'It Bangla Limited <info.genflyo@gmail.com>'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# # EMAIL_HOST_USER = 'idriveneducation@itb-usa.a2hosted.com'
# EMAIL_HOST_USER = 'info.genflyo@gmail.com'
# EMAIL_HOST_PASSWORD = 'Zaya2019!'
# DEFAULT_FROM_EMAIL = 'It Bangla Limited <info.genflyo@gmail.com>'

