# Generated by Django 4.1.1 on 2022-10-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skeleton_master',
            fields=[
                ('sk_id', models.AutoField(primary_key=True, serialize=False)),
                ('sk_desc', models.CharField(max_length=150)),
                ('sk_comments', models.CharField(max_length=150)),
                ('sk_page', models.CharField(max_length=150)),
                ('sk_place', models.CharField(max_length=150)),
                ('sk_until', models.CharField(max_length=150)),
                ('sk_loc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='skeleton_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_did', models.CharField(max_length=150)),
                ('sk_attr_name', models.CharField(max_length=150)),
                ('sk_attr_value1', models.CharField(max_length=150)),
                ('sk_attr_value2', models.CharField(max_length=150)),
                ('sk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivenapp.skeleton_master')),
            ],
        ),
    ]
